<a href="https://colab.research.google.com/github/hsadanuwan/nural_networkEx/blob/main/00_tensor_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Sumani
# 22-7-2024

# Tensor Exercises

# 1. Tensor Creation

In [ ]:
import torch
# Create a tensor of shape (5, 3) filled with random values.
random_tensor = torch.rand((5,3))
print("Random Tensor:\n", random_tensor, "\n")


Random Tensor:
 tensor([[0.1710, 0.6999, 0.5513],
        [0.7063, 0.2697, 0.3395],
        [0.5286, 0.4044, 0.4616],
        [0.0197, 0.7702, 0.4820],
        [0.9106, 0.7155, 0.4497]]) 



In [ ]:
# Create a tensor of shape (2, 4) filled with ones.
ones_tensor=torch.ones((2,4))
print("Ones tensor:\n",ones_tensor)

Ones tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# Create a tensor from a list [5, 10, 15, 20].
my_list = ((5,10,15,20))
tensor_list = torch.tensor(my_list)
print("tensor from list:\n",tensor_list)
print("Dimensions:", tensor_list.ndim)

tensor from list:
 tensor([ 5, 10, 15, 20])
Dimensions: 1


In [ ]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.
image_tensor = torch.randint(0,256,(3,6,8))
print("image tensor:\n",image_tensor)

image tensor:
 tensor([[[251,  22, 113, 147, 132, 135, 238,  40],
         [141, 247, 113,   6,  59, 251, 245, 237],
         [ 79, 240, 250, 237,   4, 245, 106, 136],
         [247, 193, 230, 169,  47, 140,  51, 236],
         [ 86, 103,  66, 241, 141,  83,  73, 147],
         [ 10,  27, 128, 252,  41,   7,  98, 117]],

        [[ 42,  82, 120, 107, 113, 115,  90,  25],
         [120, 174,  99, 219, 143, 176, 210,  42],
         [203,  68, 100, 133, 197, 218, 118,  52],
         [216, 215, 132, 239,  76,  15,   0, 222],
         [ 16, 200,   6, 124, 201, 213,  97,  35],
         [218,  88, 221,  65,  84,  40, 192,  37]],

        [[ 66,  71, 227, 149, 238, 190,  70,  90],
         [163, 122, 106, 126,  88,  35, 212, 145],
         [141,  86, 204, 158, 121, 250, 209, 186],
         [237,   8, 191, 232, 212,  32,  23, 233],
         [185,  70, 218,  87, 122, 120,  71,  47],
         [ 28, 116, 181, 249,  63,  83,  85,  82]]])


# 2. Tensor Indexing and Slicing

In [ ]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.
arange_tensor = torch.arange(10,22).reshape(3,4)
print("Arange tensor:\n",arange_tensor)


Arange tensor:
 tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [ ]:
# Access the element at the second row, third column.
element = arange_tensor[1,2]
print("element:\n",element)

element:
 tensor(16)


In [ ]:
# Print the second row.
second_row = arange_tensor[1]
print("second row:\n",second_row)

second row:
 tensor([14, 15, 16, 17])


In [ ]:
# Print the first two columns.
first_two_column = arange_tensor[:, 0:2]
print("second row:\n",first_two_column)

second row:
 tensor([[10, 11],
        [14, 15],
        [18, 19]])


# 3. Tensor Arithmetic Operations

In [ ]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.
tensor_a = torch.rand(3,3)
tensor_b = torch.rand(3,3)
print("tensor_a:\n",tensor_a)
print("tensor_b:\n",tensor_b)

tensor_a:
 tensor([[0.2743, 0.8306, 0.9516],
        [0.3555, 0.5665, 0.9559],
        [0.7639, 0.3271, 0.1510]])
tensor_b:
 tensor([[0.2037, 0.9836, 0.0806],
        [0.0224, 0.5216, 0.0982],
        [0.3684, 0.6731, 0.4883]])


In [ ]:
# Perform element-wise addition.
total = tensor_a + tensor_b
print("Total:\n",total)

Total:
 tensor([[0.4780, 1.8142, 1.0322],
        [0.3779, 1.0881, 1.0541],
        [1.1323, 1.0001, 0.6393]])


In [ ]:
# Perform element-wise multiplication.
multiplication = tensor_a * tensor_b
print("multiplication:\n",multiplication)

multiplication:
 tensor([[0.0559, 0.8170, 0.0767],
        [0.0080, 0.2955, 0.0939],
        [0.2814, 0.2201, 0.0738]])


In [ ]:
# Subtract tensor_b from tensor_a.
Subtract = tensor_b - tensor_a
print("Subtract:\n",Subtract)

Subtract:
 tensor([[-0.0706,  0.1531, -0.8710],
        [-0.3331, -0.0449, -0.8577],
        [-0.3955,  0.3460,  0.3373]])


# 4. Tensor Aggregation Operations

In [ ]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.
agg_tensor=torch.arange(1,10).reshape(3,3)
print("Aggregation Tensor:\n",agg_tensoror )

Aggregation Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
# Compute the sum of all elements.
total_sum = agg_tensor.sum()
print("Aggregation Tensor sun:\n",total_sum )

Aggregation Tensor sun:
 tensor(45)


In [ ]:
# Compute the mean of all elements.
mean = agg_tensor.float().mean()
print(" Tensor Mean:\n",mean )

 Tensor Mean:
 tensor(5.)


In [ ]:
# Find the maximum and minimum values.
max = agg_tensor.max()
min = agg_tensor.min()
print(" Tensor Max:\n",max )
print(" Tensor Min:\n",min )

 Tensor Max:
 tensor(9)
 Tensor Min:
 tensor(1)


In [ ]:
# Compute the sum along the rows.
row_sum = agg_tensor.sum(dim=1)
print("Row sum:\n",row_sum )

Row sum:
 tensor([ 6, 15, 24])


In [ ]:
# Compute the mean along the columns.
mean = agg_tensor.float().mean(dim=0)
print(" Tensor Mean:\n",mean )

 Tensor Mean:
 tensor([4., 5., 6.])


# 5. Tensor Reshaping Operations

In [ ]:
# Create a tensor tensor of shape (2, 3, 4) with random values.
shape_rand=torch.rand((2,3,4))
print(" Tensor shape:\n",shape_rand.shape )

 Tensor shape:
 torch.Size([2, 3, 4])


In [ ]:
# Reshape the tensor to (4, 6).
reshape_rand=shape_rand.reshape((4,6))
print(" Tensor shape:\n",reshape_rand)

 Tensor shape:
 tensor([[0.6589, 0.8935, 0.1347, 0.8348, 0.8643, 0.0589],
        [0.6171, 0.6220, 0.0035, 0.0653, 0.8357, 0.3612],
        [0.1654, 0.9123, 0.5115, 0.1830, 0.6020, 0.4335],
        [0.0391, 0.5478, 0.5028, 0.1221, 0.2687, 0.6783]])


In [ ]:
# Transpose the tensor (swap the first and second dimensions).
transpose_tensor = shape_rand.transpose(0,1)
print("Transpose:\n",transpose_tensor)

Transpose:
 tensor([[[0.6589, 0.8935, 0.1347, 0.8348],
         [0.1654, 0.9123, 0.5115, 0.1830]],

        [[0.8643, 0.0589, 0.6171, 0.6220],
         [0.6020, 0.4335, 0.0391, 0.5478]],

        [[0.0035, 0.0653, 0.8357, 0.3612],
         [0.5028, 0.1221, 0.2687, 0.6783]]])


In [ ]:
# Flatten the tensor to a 1D tensor.
transpose_tensor = shape_rand.transpose(0,1)
print("Transpose:\n",transpose_tensor)

Transpose:
 tensor([[[0.6589, 0.8935, 0.1347, 0.8348],
         [0.1654, 0.9123, 0.5115, 0.1830]],

        [[0.8643, 0.0589, 0.6171, 0.6220],
         [0.6020, 0.4335, 0.0391, 0.5478]],

        [[0.0035, 0.0653, 0.8357, 0.3612],
         [0.5028, 0.1221, 0.2687, 0.6783]]])


# 6. Tensor Broadcasting

In [ ]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.
tensor_a = torch.arange(1,7).reshape(2,3)
print("tensor_a:\n",tensor_a )


tensor_a:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].
tensor_b = torch.tensor((1,2,3))
print("tensor_b shape:\n", tensor_b.shape)
print("tensor_a:\n",tensor_b )

tensor_b shape:
 torch.Size([3])
tensor_a:
 tensor([1, 2, 3])


In [ ]:
# Perform broadcasting addition.
result = tensor_a + tensor_b
print("Broadcast Addition Result:\n", result)

Broadcast Addition Result:
 tensor([[2, 4, 6],
        [5, 7, 9]])


In [ ]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].
tensor_c = torch.tensor([[1], [2], [3]])

print("tensor_c shape:", tensor_c.shape)
print("tensor_c:\n", tensor_c)

tensor_c shape: torch.Size([3, 1])
tensor_c:
 tensor([[1],
        [2],
        [3]])


In [ ]:
# Perform broadcasting multiplication.
result = tensor_b * tensor_c

print("tensor_b (1, 3):\n", tensor_b)
print("tensor_c (3, 1):\n", tensor_c)
print("Broadcasted Multiplication Result (3, 3):\n", result)

tensor_b (1, 3):
 tensor([1, 2, 3])
tensor_c (3, 1):
 tensor([[1],
        [2],
        [3]])
Broadcasted Multiplication Result (3, 3):
 tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])


# 7. Tensor Device Management

In [ ]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).
device = torch.device("gpu" if torch.cuda.is_available() else "cpu")
tensor = torch.rand((3, 3), device=device)

print("Device:", tensor.device)
print("Tensor:\n", tensor)


Device: cpu
Tensor:
 tensor([[0.4984, 0.2228, 0.3519],
        [0.1305, 0.6292, 0.7713],
        [0.3368, 0.9702, 0.1657]])


In [ ]:
# Verify if the tensor is on GPU.
if tensor.is_cuda:
    print("Tensor is on GPU:", tensor.device)
else:
    print("Tensor is on CPU.")
# Move the tensor back to CPU.

tensor_cpu = tensor.cpu()

print("Moved tensor back to:", tensor_cpu.device)

Tensor is on CPU.
Moved tensor back to: cpu


# 8. Tensor Cloning and Detaching

In [ ]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.
tensor = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print("Tensor:", tensor)

Tensor: tensor([1., 2., 3.], requires_grad=True)


In [ ]:
# Clone the tensor and print the cloned tensor.
cloned_tensor = tensor.clone()
print("Cloned tensor:\n", cloned_tensor)


Cloned tensor:
 tensor([1., 2., 3.], grad_fn=<CloneBackward0>)


In [ ]:
# Detach the tensor from the computation graph and print the detached tensor.
detached_tensor = tensor.detach()
print("Original tensor (requires_grad=True):\n", tensor)
print("Detached tensor :\n", detached_tensor)

Original tensor (requires_grad=True):
 tensor([1., 2., 3.], requires_grad=True)
Detached tensor :
 tensor([1., 2., 3.])


# 9. High Dimensional Tensors

In [ ]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.
tensor = torch.rand((2, 3, 4, 5))
print("Tensor:\n", tensor)

Tensor:
 tensor([[[[0.8506, 0.7663, 0.9532, 0.4635, 0.1664],
          [0.4312, 0.2447, 0.7688, 0.2678, 0.0436],
          [0.6579, 0.8655, 0.9353, 0.3475, 0.9425],
          [0.3214, 0.1015, 0.1933, 0.1874, 0.6317]],

         [[0.8130, 0.3463, 0.2954, 0.1583, 0.2021],
          [0.6830, 0.4868, 0.3854, 0.5713, 0.8268],
          [0.5579, 0.9061, 0.9916, 0.6566, 0.4958],
          [0.5972, 0.4385, 0.9466, 0.0925, 0.4778]],

         [[0.2799, 0.1127, 0.1394, 0.2841, 0.7426],
          [0.8214, 0.4630, 0.1776, 0.8029, 0.9555],
          [0.7165, 0.8881, 0.0881, 0.4574, 0.4893],
          [0.7500, 0.6129, 0.7906, 0.5119, 0.3953]]],


        [[[0.2047, 0.2592, 0.4018, 0.5175, 0.4670],
          [0.1648, 0.8836, 0.6551, 0.3126, 0.1959],
          [0.7995, 0.0560, 0.2614, 0.2364, 0.6015],
          [0.1164, 0.1494, 0.0611, 0.1184, 0.6187]],

         [[0.7636, 0.4656, 0.8191, 0.3029, 0.8304],
          [0.2647, 0.7080, 0.5261, 0.2963, 0.1292],
          [0.7818, 0.9145, 0.8092, 0.1726, 0.

In [ ]:
# Print the shape of the tensor.
print("Tensor shape:", tensor.shape)


Tensor shape: torch.Size([2, 3, 4, 5])


In [ ]:
# Access the element at position (1, 2, 3, 4).
element = tensor[1, 2, 3, 4]

print("Element at position (1, 2, 3, 4):", element.item())

Element at position (1, 2, 3, 4): 0.24797481298446655


In [ ]:
# Slice and print the first two elements along the first dimension.
sliced_tensor = tensor[:2]
print("Sliced tensor:\n", sliced_tensor)

Sliced tensor:
 tensor([[[[0.8506, 0.7663, 0.9532, 0.4635, 0.1664],
          [0.4312, 0.2447, 0.7688, 0.2678, 0.0436],
          [0.6579, 0.8655, 0.9353, 0.3475, 0.9425],
          [0.3214, 0.1015, 0.1933, 0.1874, 0.6317]],

         [[0.8130, 0.3463, 0.2954, 0.1583, 0.2021],
          [0.6830, 0.4868, 0.3854, 0.5713, 0.8268],
          [0.5579, 0.9061, 0.9916, 0.6566, 0.4958],
          [0.5972, 0.4385, 0.9466, 0.0925, 0.4778]],

         [[0.2799, 0.1127, 0.1394, 0.2841, 0.7426],
          [0.8214, 0.4630, 0.1776, 0.8029, 0.9555],
          [0.7165, 0.8881, 0.0881, 0.4574, 0.4893],
          [0.7500, 0.6129, 0.7906, 0.5119, 0.3953]]],


        [[[0.2047, 0.2592, 0.4018, 0.5175, 0.4670],
          [0.1648, 0.8836, 0.6551, 0.3126, 0.1959],
          [0.7995, 0.0560, 0.2614, 0.2364, 0.6015],
          [0.1164, 0.1494, 0.0611, 0.1184, 0.6187]],

         [[0.7636, 0.4656, 0.8191, 0.3029, 0.8304],
          [0.2647, 0.7080, 0.5261, 0.2963, 0.1292],
          [0.7818, 0.9145, 0.8092, 0.1

In [ ]:
# Sum all elements in the tensor.
total_sum = tensor.sum()

print("Sum of all elements:", total_sum.item())

Sum of all elements: 58.85488510131836


In [ ]:
# Compute the mean along the third dimension.
mean_along_dim3 = tensor.mean(dim=2)
print(mean_along_dim3)

tensor([[[0.5653, 0.4945, 0.7127, 0.3165, 0.4460],
         [0.6628, 0.5445, 0.6548, 0.3697, 0.5006],
         [0.6419, 0.5192, 0.2989, 0.5141, 0.6457]],

        [[0.3213, 0.3371, 0.3449, 0.2962, 0.4708],
         [0.6860, 0.5606, 0.7657, 0.3082, 0.4359],
         [0.3072, 0.5153, 0.6599, 0.5643, 0.2535]]])


# 10. Combining Tensor Operations

In [ ]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.
tensor_a = torch.rand((2, 3, 4))
tensor_b = torch.rand((2, 3, 4))

print("tensor_a:\n", tensor_a)
print("\ntensor_b:\n", tensor_b)

tensor_a:
 tensor([[[0.7723, 0.0605, 0.0817, 0.7494],
         [0.9457, 0.7759, 0.6000, 0.0331],
         [0.0603, 0.2260, 0.7794, 0.8668]],

        [[0.2055, 0.1002, 0.1732, 0.3006],
         [0.1338, 0.8436, 0.0894, 0.1517],
         [0.6311, 0.5508, 0.7932, 0.8376]]])

tensor_b:
 tensor([[[0.5860, 1.0000, 0.2162, 0.0663],
         [0.9034, 0.0789, 0.5729, 0.5648],
         [0.4074, 0.4089, 0.2853, 0.3268]],

        [[0.6495, 0.6362, 0.7096, 0.6953],
         [0.5589, 0.7143, 0.8394, 0.5731],
         [0.4832, 0.8306, 0.7224, 0.8040]]])


In [ ]:
# Add the two tensors.
result = tensor_a + tensor_b
print("Result of Addition:\n", result)

Result of Addition:
 tensor([[[1.3583, 1.0605, 0.2979, 0.8157],
         [1.8491, 0.8548, 1.1729, 0.5980],
         [0.4677, 0.6349, 1.0647, 1.1936]],

        [[0.8550, 0.7364, 0.8828, 0.9959],
         [0.6927, 1.5580, 0.9288, 0.7248],
         [1.1143, 1.3814, 1.5156, 1.6416]]])


In [ ]:
# Multiply the resulting tensor by 2.
scaled_result = result * 2
print("Scaled Result :\n", scaled_result)

Scaled Result :
 tensor([[[2.7166, 2.1210, 0.5958, 1.6313],
         [3.6982, 1.7097, 2.3459, 1.1959],
         [0.9354, 1.2699, 2.1294, 2.3872]],

        [[1.7100, 1.4728, 1.7655, 1.9917],
         [1.3853, 3.1159, 1.8577, 1.4495],
         [2.2285, 2.7628, 3.0312, 3.2833]]])


In [ ]:
# Reshape the tensor to (4, 6).
reshaped = result.reshape(4, 6)
print("Reshaped tensor:\n", reshaped)

Reshaped tensor:
 tensor([[1.3583, 1.0605, 0.2979, 0.8157, 1.8491, 0.8548],
        [1.1729, 0.5980, 0.4677, 0.6349, 1.0647, 1.1936],
        [0.8550, 0.7364, 0.8828, 0.9959, 0.6927, 1.5580],
        [0.9288, 0.7248, 1.1143, 1.3814, 1.5156, 1.6416]])


In [ ]:
# Compute the sum along the columns.
column_sums = reshaped.sum(dim=0)
print("Sum along columns :\n", column_sums)

Sum along columns :
 tensor([4.3151, 3.1196, 2.7626, 3.8279, 5.1221, 5.2480])


-------------------------------------------- END ----------------------------------------------